### ISSUE TITLE
control class spell bug

### ISSUE THREAD

**Issue by mpfans** [H0zen/M0-server#23]
wizard's 'Enslave Demon' spell (id=1098) and Priest's 'Dominate Mind' spell (id=605) ,Controlled monster cast spell no cd !

Hurt a little higher can spike all the elite strange

**Comment by mpfans** [comment]
Can test under the 'Helboar'


http://wow.magelo.com/en/npc/5993

**Comment by H0zen** [comment]
This issue was moved to H0zen/mangos-issues#23
