### ISSUE TITLE
Door of the 'Ras Frostwhisper'  room 

### ISSUE THREAD

**Issue by mpfans** [H0zen/M0-server#33]
This door does not open the GM mode, it can not be opened

in Scholomance instance

**Comment by mpfans** [comment]
.gobject near
43195 entry 177370-[door x:57.480202 Y:142.856003 Z: 83.479599 Mapid:289]

**Comment by H0zen** [comment]
`UPDATE `gameobject` SET `state` = 0 WHERE `guid` = 43195;`

**Comment by mpfans** [comment]
ok! The bug is solved.
